# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gpssetup_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(540, 477)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.gbTimebase = QtWidgets.QGroupBox(Form)
        self.gbTimebase.setObjectName("gbTimebase")
        self.formLayout = QtWidgets.QFormLayout(self.gbTimebase)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.gbTimebase)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lock_to_gps_label = QtWidgets.QLabel(self.gbTimebase)
        self.lock_to_gps_label.setObjectName("lock_to_gps_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lock_to_gps_label)
        self.label_5 = QtWidgets.QLabel(self.gbTimebase)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.loop_bandwidth_label = QtWidgets.QLabel(self.gbTimebase)
        self.loop_bandwidth_label.setObjectName("loop_bandwidth_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.loop_bandwidth_label)
        self.label = QtWidgets.QLabel(self.gbTimebase)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.manual_time_constant_label = QtWidgets.QLabel(self.gbTimebase)
        self.manual_time_constant_label.setObjectName("manual_time_constant_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.manual_time_constant_label)
        self.label_2 = QtWidgets.QLabel(self.gbTimebase)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.holdover_error_label = QtWidgets.QLabel(self.gbTimebase)
        self.holdover_error_label.setObjectName("holdover_error_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.holdover_error_label)
        self.label_3 = QtWidgets.QLabel(self.gbTimebase)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.leave_holdover_label = QtWidgets.QLabel(self.gbTimebase)
        self.leave_holdover_label.setObjectName("leave_holdover_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.leave_holdover_label)
        self.edit_timebase_btn = QtWidgets.QPushButton(self.gbTimebase)
        self.edit_timebase_btn.setObjectName("edit_timebase_btn")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.edit_timebase_btn)
        self.gridLayout.addWidget(self.gbTimebase, 0, 0, 1, 1)
        self.gbDeviceInfo = QtWidgets.QGroupBox(Form)
        self.gbDeviceInfo.setObjectName("gbDeviceInfo")
        self.formLayout_2 = QtWidgets.QFormLayout(self.gbDeviceInfo)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.gbDeviceInfo)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.serial_number_label = QtWidgets.QLabel(self.gbDeviceInfo)
        self.serial_number_label.setObjectName("serial_number_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.serial_number_label)
        self.label_7 = QtWidgets.QLabel(self.gbDeviceInfo)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.firmware_version_label = QtWidgets.QLabel(self.gbDeviceInfo)
        self.firmware_version_label.setObjectName("firmware_version_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.firmware_version_label)
        self.gnss_receiver_caption = QtWidgets.QLabel(self.gbDeviceInfo)
        self.gnss_receiver_caption.setObjectName("gnss_receiver_caption")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.gnss_receiver_caption)
        self.gnss_receiver_label = QtWidgets.QLabel(self.gbDeviceInfo)
        self.gnss_receiver_label.setText("")
        self.gnss_receiver_label.setObjectName("gnss_receiver_label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.gnss_receiver_label)
        self.gnss_version_caption = QtWidgets.QLabel(self.gbDeviceInfo)
        self.gnss_version_caption.setObjectName("gnss_version_caption")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.gnss_version_caption)
        self.receiver_version_label = QtWidgets.QLabel(self.gbDeviceInfo)
        self.receiver_version_label.setText("")
        self.receiver_version_label.setObjectName("receiver_version_label")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.receiver_version_label)
        self.label_18 = QtWidgets.QLabel(self.gbDeviceInfo)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.model_label = QtWidgets.QLabel(self.gbDeviceInfo)
        self.model_label.setObjectName("model_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.model_label)
        self.label_20 = QtWidgets.QLabel(self.gbDeviceInfo)
        self.label_20.setObjectName("label_20")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.options_label = QtWidgets.QLabel(self.gbDeviceInfo)
        self.options_label.setText("")
        self.options_label.setObjectName("options_label")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.options_label)
        self.gridLayout.addWidget(self.gbDeviceInfo, 0, 1, 1, 1)
        self.gbReceiver = QtWidgets.QGroupBox(Form)
        self.gbReceiver.setObjectName("gbReceiver")
        self.formLayout_3 = QtWidgets.QFormLayout(self.gbReceiver)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_10 = QtWidgets.QLabel(self.gbReceiver)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.timing_alignment_label = QtWidgets.QLabel(self.gbReceiver)
        self.timing_alignment_label.setObjectName("timing_alignment_label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.timing_alignment_label)
        self.label_11 = QtWidgets.QLabel(self.gbReceiver)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.timing_quality_label = QtWidgets.QLabel(self.gbReceiver)
        self.timing_quality_label.setObjectName("timing_quality_label")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.timing_quality_label)
        self.label_12 = QtWidgets.QLabel(self.gbReceiver)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_14 = QtWidgets.QLabel(self.gbReceiver)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.gbReceiver)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_13 = QtWidgets.QLabel(self.gbReceiver)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.edit_receiver_btn = QtWidgets.QPushButton(self.gbReceiver)
        self.edit_receiver_btn.setObjectName("edit_receiver_btn")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.edit_receiver_btn)
        self.position_survey_label = QtWidgets.QLabel(self.gbReceiver)
        self.position_survey_label.setObjectName("position_survey_label")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.position_survey_label)
        self.position_fixes_label = QtWidgets.QLabel(self.gbReceiver)
        self.position_fixes_label.setObjectName("position_fixes_label")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.position_fixes_label)
        self.antenna_correction_label = QtWidgets.QLabel(self.gbReceiver)
        self.antenna_correction_label.setObjectName("antenna_correction_label")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.antenna_correction_label)
        self.local_time_offset_label = QtWidgets.QLabel(self.gbReceiver)
        self.local_time_offset_label.setObjectName("local_time_offset_label")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.local_time_offset_label)
        self.constellations_caption = QtWidgets.QLabel(self.gbReceiver)
        self.constellations_caption.setObjectName("constellations_caption")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.constellations_caption)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.track_gps_checkbox = ReadOnlyCheckBox(self.gbReceiver)
        self.track_gps_checkbox.setObjectName("track_gps_checkbox")
        self.verticalLayout_4.addWidget(self.track_gps_checkbox)
        self.track_glonass_checkbox = ReadOnlyCheckBox(self.gbReceiver)
        self.track_glonass_checkbox.setObjectName("track_glonass_checkbox")
        self.verticalLayout_4.addWidget(self.track_glonass_checkbox)
        self.track_beidou_checkbox = ReadOnlyCheckBox(self.gbReceiver)
        self.track_beidou_checkbox.setObjectName("track_beidou_checkbox")
        self.verticalLayout_4.addWidget(self.track_beidou_checkbox)
        self.track_galileo_checkbox = ReadOnlyCheckBox(self.gbReceiver)
        self.track_galileo_checkbox.setObjectName("track_galileo_checkbox")
        self.verticalLayout_4.addWidget(self.track_galileo_checkbox)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_4)
        self.label_8 = QtWidgets.QLabel(self.gbReceiver)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.min_snr_label = QtWidgets.QLabel(self.gbReceiver)
        self.min_snr_label.setObjectName("min_snr_label")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.min_snr_label)
        self.label_9 = QtWidgets.QLabel(self.gbReceiver)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.min_sat_elevation_label = QtWidgets.QLabel(self.gbReceiver)
        self.min_sat_elevation_label.setObjectName("min_sat_elevation_label")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.min_sat_elevation_label)
        self.gridLayout.addWidget(self.gbReceiver, 1, 0, 2, 1)
        self.gbAlarm = QtWidgets.QGroupBox(Form)
        self.gbAlarm.setObjectName("gbAlarm")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbAlarm)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_16 = QtWidgets.QLabel(self.gbAlarm)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.alarm_mode_label = QtWidgets.QLabel(self.gbAlarm)
        self.alarm_mode_label.setObjectName("alarm_mode_label")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.alarm_mode_label)
        self.label_17 = QtWidgets.QLabel(self.gbAlarm)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.verticalLayout_3.addLayout(self.formLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.not_from_gps_checkbox = ReadOnlyCheckBox(self.gbAlarm)
        self.not_from_gps_checkbox.setObjectName("not_from_gps_checkbox")
        self.verticalLayout.addWidget(self.not_from_gps_checkbox)
        self.in_holdver_checkbox = ReadOnlyCheckBox(self.gbAlarm)
        self.in_holdver_checkbox.setObjectName("in_holdver_checkbox")
        self.verticalLayout.addWidget(self.in_holdver_checkbox)
        self.offset_from_utc_checkbox = ReadOnlyCheckBox(self.gbAlarm)
        self.offset_from_utc_checkbox.setObjectName("offset_from_utc_checkbox")
        self.verticalLayout.addWidget(self.offset_from_utc_checkbox)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_alarm_btn = QtWidgets.QPushButton(self.gbAlarm)
        self.edit_alarm_btn.setObjectName("edit_alarm_btn")
        self.horizontalLayout.addWidget(self.edit_alarm_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.gridLayout.addWidget(self.gbAlarm, 1, 1, 1, 1)
        self.gbPulse = QtWidgets.QGroupBox(Form)
        self.gbPulse.setObjectName("gbPulse")
        self.formLayout_5 = QtWidgets.QFormLayout(self.gbPulse)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_19 = QtWidgets.QLabel(self.gbPulse)
        self.label_19.setObjectName("label_19")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.time_offset_label = QtWidgets.QLabel(self.gbPulse)
        self.time_offset_label.setObjectName("time_offset_label")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.time_offset_label)
        self.edit_1pps_btn = QtWidgets.QPushButton(self.gbPulse)
        self.edit_1pps_btn.setObjectName("edit_1pps_btn")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_1pps_btn)
        self.gridLayout.addWidget(self.gbPulse, 2, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.edit_timebase_btn, self.edit_receiver_btn)
        Form.setTabOrder(self.edit_receiver_btn, self.edit_alarm_btn)
        Form.setTabOrder(self.edit_alarm_btn, self.not_from_gps_checkbox)
        Form.setTabOrder(self.not_from_gps_checkbox, self.in_holdver_checkbox)
        Form.setTabOrder(self.in_holdver_checkbox, self.offset_from_utc_checkbox)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.gbTimebase.setTitle(_translate("Form", "Timebase"))
        self.label_4.setText(_translate("Form", "Lock to GNSS:"))
        self.lock_to_gps_label.setText(_translate("Form", "Yes"))
        self.label_5.setText(_translate("Form", "Loop Bandwidth:"))
        self.loop_bandwidth_label.setText(_translate("Form", "Automatic"))
        self.label.setText(_translate("Form", "Manual Loop TC:"))
        self.manual_time_constant_label.setText(_translate("Form", "250 s"))
        self.label_2.setText(_translate("Form", "Enter holdover if error >"))
        self.holdover_error_label.setText(_translate("Form", "1.0 us"))
        self.label_3.setText(_translate("Form", "To leave holdover:"))
        self.leave_holdover_label.setText(_translate("Form", "Jump to good 1pps"))
        self.edit_timebase_btn.setText(_translate("Form", "Edit"))
        self.gbDeviceInfo.setTitle(_translate("Form", "Device Info"))
        self.label_6.setText(_translate("Form", "Serial Number:"))
        self.serial_number_label.setText(_translate("Form", "s/n000000"))
        self.label_7.setText(_translate("Form", "Firmware Version:"))
        self.firmware_version_label.setText(_translate("Form", "0.00"))
        self.gnss_receiver_caption.setText(_translate("Form", "GNSS Receiver:"))
        self.gnss_version_caption.setText(_translate("Form", "Receiver Version:"))
        self.label_18.setText(_translate("Form", "Model:"))
        self.model_label.setText(_translate("Form", "FS752"))
        self.label_20.setText(_translate("Form", "Options:"))
        self.gbReceiver.setTitle(_translate("Form", "GNSS Receiver"))
        self.label_10.setText(_translate("Form", "Timing Alignment:"))
        self.timing_alignment_label.setText(_translate("Form", "Align to UTC"))
        self.label_11.setText(_translate("Form", "Timing Quality:"))
        self.timing_quality_label.setText(_translate("Form", "Require 3 satellites"))
        self.label_12.setText(_translate("Form", "Position Survey:"))
        self.label_14.setText(_translate("Form", "Position Fixes in Survey:"))
        self.label_15.setText(_translate("Form", "Antenna Delay Correction:"))
        self.label_13.setText(_translate("Form", "Local Time Offset:"))
        self.edit_receiver_btn.setText(_translate("Form", "Edit"))
        self.position_survey_label.setText(_translate("Form", "Disabled"))
        self.position_fixes_label.setText(_translate("Form", "2000"))
        self.antenna_correction_label.setText(_translate("Form", "0 ns"))
        self.local_time_offset_label.setText(_translate("Form", "0 hr"))
        self.constellations_caption.setText(_translate("Form", "Constellations Tracked:"))
        self.track_gps_checkbox.setText(_translate("Form", "GPS"))
        self.track_glonass_checkbox.setText(_translate("Form", "GLONASS"))
        self.track_beidou_checkbox.setText(_translate("Form", "BEIDOU"))
        self.track_galileo_checkbox.setText(_translate("Form", "GALILEO"))
        self.label_8.setText(_translate("Form", "Minimum SNR:"))
        self.min_snr_label.setText(_translate("Form", "20"))
        self.label_9.setText(_translate("Form", "Minimum Sat. Elevation:"))
        self.min_sat_elevation_label.setText(_translate("Form", "5 deg"))
        self.gbAlarm.setTitle(_translate("Form", "Alarm"))
        self.label_16.setText(_translate("Form", "Mode:"))
        self.alarm_mode_label.setText(_translate("Form", "Manually set state"))
        self.label_17.setText(_translate("Form", "Assert alarm if:"))
        self.not_from_gps_checkbox.setText(_translate("Form", "Time not from GPS"))
        self.in_holdver_checkbox.setText(_translate("Form", "In holdover for more than 0 s"))
        self.offset_from_utc_checkbox.setText(_translate("Form", "Offset from UTC more than 100 ns"))
        self.edit_alarm_btn.setText(_translate("Form", "Edit"))
        self.gbPulse.setTitle(_translate("Form", "1pps Output"))
        self.label_19.setText(_translate("Form", "Time Offset:"))
        self.time_offset_label.setText(_translate("Form", "0 ns"))
        self.edit_1pps_btn.setText(_translate("Form", "Edit"))

from readonly_checkbox import ReadOnlyCheckBox
